[package]
name = "marktex-core"
version = "0.1.0"
edition = "2024"

[dependencies]
comrak = "0.50.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

[dev-dependencies]
datatest-stable = "0.3"

[[test]]
name = "golden"
harness = false
