[package]
name = "marktex-core"
version = "0.4.0"
edition = "2024"

[dependencies]
comrak = "0.50.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = { package = "serde_yaml_ng", version = "0.10.0" }

[dev-dependencies]
datatest-stable = "0.3"

[[test]]
name = "golden"
harness = false
